# We need to make sure the checked-in `dist/index.js` actually matches what we expect it to be.
name: check dist/

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  check-dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Check for non-doc changes
        id: filter
        uses: dorny/paths-filter@v4
        with:
          filters: |
            src:
              - '!**.md'
      - name: Set Node.js 22.x
        if: steps.filter.outputs.src == 'true'
        uses: actions/setup-node@v7.0.0
        with:
          node-version: 22.x
      - name: Install dependencies
        if: steps.filter.outputs.src == 'true'
        run: npm ci
      - name: Rebuild the dist/ directory
        if: steps.filter.outputs.src == 'true'
        run: npm run prepare
      - name: Verify dist/ is up to date
        if: steps.filter.outputs.src == 'true'
        run: |
          if [ -n "$(git diff --ignore-space-at-eol dist/)" ]; then
            echo "::error::dist/ is out of date. Comment /rebuild on this PR to regenerate and push it."
            git diff dist/
            exit 1
          fi
