name: "units-test"
on:
  pull_request:

jobs:
  # compile
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: npm ci

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    env:
        OUTPUT_VALUE: overloaded output value
    steps:
    - uses: actions/checkout@v3
    - uses: ./
      with:
        project-slug: ${{ github.repository }}
        user-token: ${{ secrets.CIRCLECI_TOKEN }}
        branch: ${{ github.head_ref }} # in pull request context we can just use this
        payload: '{"run_output_workflow": true, "output_value": "${{ env.OUTPUT_VALUE }}"}'
