name: "smoke-test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  smoke:
    runs-on: ubuntu-latest
    env:
        OUTPUT_VALUE: overloaded output value
    steps:
    - name: Capture triggering branch name
      run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
    - uses: promiseofcake/circleci-trigger-action@v1
      with:
        user-token: ${{ secrets.CIRCLECI_TOKEN }}
        project-slug: ${{ github.repository }}
        branch: ${{ env.BRANCH_NAME }}
        payload: '{"run_output_workflow": true, "output_value": "${{ env.OUTPUT_VALUE }}"}'
